### PR TITLE
darkmode

### PR DESCRIPTION
**Pull request by ReadingOwl3000**
darkmode for the opner

### CODE REVIEW

**Comment by ReadingOwl3000** [comment]
darkmode du weißt

**Review by mvo5 — COMMENTED** [review]
Thank you! This is very nice - I'm happy to merge this but the indent is a bit uneven and the pubspec.yaml changes are unrelated to this PR so they should be reverted (and maybe become their own PR?)

**Comment by mvo5** [comment]
I looked at this again and it seems there is already support in flutter for this, I opened https://github.com/mvo5/flutter-opener/pull/10 which will simply follow the device default setting.

**Comment by mvo5** [comment]
Please test and let me know, I am happy to reopen this PR if the other one is not quite sufficient.

**Pull request closed without merging**
